# SPDX-FileCopyrightText: Public Domain
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "Npp.DotNet.Templates"
SPDX-PackageSupplier = "Npp.NET Team <https://github.com/npp-dotnet>"
SPDX-PackageDownloadLocation = "https://www.nuget.org/packages/npp.dotnet.templates"

[[annotations]]
path = ["COPYING"]
SPDX-FileCopyrightText = "2004 Apache Software Foundation"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["**.cs", "**.csproj", "**.sln"]
SPDX-FileCopyrightText = "2025 Npp.NET Team and Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["**/CODEOWNERS", "**/.gitignore", "**.json", "**.md", "**.bmp", "**.ico", "**.png", "**.props", "**.pubxml", "**.resx", "**.user"]
SPDX-FileCopyrightText = "Public Domain"
SPDX-License-Identifier = "CC0-1.0"
